version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src/utils/qr_codes:/usr/src/app/src/utils/qr_codes # Map QR code storage
      - /usr/src/app/node_modules # Node modules volume
    env_file: 
      - .env
    environment:
      - NODE_ENV=production
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db # Persist MongoDB data

volumes:
  mongodb_data:
