@echo off
REM ============================================================================
REM ReliefJet Mail Merge Automation Script
REM ============================================================================
REM This script runs ReliefJet Essentials CLI to perform mail merge
REM Prerequisites:
REM   - ReliefJet Essentials Professional Edition installed
REM   - Outlook configured on this machine
REM   - CSV file generated by exportForReliefJet.js
REM ============================================================================

echo.
echo ============================================================================
echo ReliefJet Mail Merge Automation
echo ============================================================================
echo.

REM ============================================================================
REM CONFIGURATION - MODIFY THESE PATHS ACCORDING TO YOUR SETUP
REM ============================================================================

REM Path to ReliefJet ExecutorCli.exe
REM Default installation path is usually:
REM   C:\Program Files (x86)\Relief Software\ReliefJet Essentials for Outlook\ExecutorCli.exe
REM Adjust this path if ReliefJet is installed elsewhere
SET RELIEFJET_PATH="C:\Program Files (x86)\Relief Software\ReliefJet Essentials for Outlook\ExecutorCli.exe"

REM Path to the CSV data source (generated by exportForReliefJet.js)
SET CSV_PATH="%~dp0reliefjet_mailmerge.csv"

REM Path to Outlook email template (.oft or .msg file)
REM You need to create this template in Outlook with merge fields
REM Example merge fields: <<Email1>>, <<QRCodePath>>, <<ValidationURL>>
SET TEMPLATE_PATH="%~dp0email_template.oft"

REM Outlook profile name (leave empty to use default profile)
SET OUTLOOK_PROFILE=

REM Output folder for sent items (optional)
REM Leave empty to use default Sent Items folder
SET SENT_FOLDER=

REM ============================================================================
REM VALIDATION
REM ============================================================================

echo [1/4] Validating paths...

if not exist %RELIEFJET_PATH% (
    echo ERROR: ReliefJet ExecutorCli.exe not found at:
    echo %RELIEFJET_PATH%
    echo.
    echo Please update RELIEFJET_PATH in this script with the correct path.
    echo You can find ExecutorCli.exe in your ReliefJet installation directory.
    echo.
    pause
    exit /b 1
)

if not exist %CSV_PATH% (
    echo ERROR: CSV data source not found at:
    echo %CSV_PATH%
    echo.
    echo Please run: npm run export-reliefjet
    echo This will generate the CSV file with email addresses and QR code paths.
    echo.
    pause
    exit /b 1
)

if not exist %TEMPLATE_PATH% (
    echo ERROR: Email template not found at:
    echo %TEMPLATE_PATH%
    echo.
    echo Please create an Outlook email template (.oft file) with merge fields:
    echo   - ^<^<Email1^>^> for recipient email
    echo   - ^<^<QRCodePath^>^> for QR code attachment
    echo   - ^<^<ValidationURL^>^> for validation link (optional)
    echo.
    echo Save the template to: %TEMPLATE_PATH%
    echo.
    pause
    exit /b 1
)

echo [OK] All paths validated successfully.
echo.

REM ============================================================================
REM DETERMINE UTILITY CODE
REM ============================================================================

echo [2/4] ReliefJet utility information...
echo.
echo NOTE: To find the exact utility code for Mail Merge, run:
echo %RELIEFJET_PATH%
echo.
echo Then type "mail" or "merge" to search for the Mail Merge utility code.
echo Common utility codes based on ReliefJet naming conventions:
echo   - OutlookMessagesMailMerge
echo   - OutlookMailMerge
echo.
echo If you know the utility code, update this script accordingly.
echo.

REM The utility code - you need to verify this by running ExecutorCli search
REM Run ExecutorCli.exe without parameters and search for "mail merge"
SET UTILITY_CODE=OutlookMessagesMailMerge

echo Using utility code: %UTILITY_CODE%
echo.

REM ============================================================================
REM COMMAND LINE PARAMETERS
REM ============================================================================

echo [3/4] Building command line parameters...

REM Build the ExecutorCli command
REM Based on ReliefJet documentation, parameters vary by utility
REM You may need to adjust these parameters based on your ReliefJet version
REM Run: ExecutorCli -? -u %UTILITY_CODE% to see available parameters

SET COMMAND=%RELIEFJET_PATH% -v -u %UTILITY_CODE%

REM Add common parameters
if not "%OUTLOOK_PROFILE%"=="" (
    SET COMMAND=%COMMAND% -pProfile="%OUTLOOK_PROFILE%"
)

REM Mail merge specific parameters (adjust based on actual utility requirements)
REM These are educated guesses based on typical mail merge tools
REM You MUST verify these with: ExecutorCli -? -u OutlookMessagesMailMerge
SET COMMAND=%COMMAND% DataSource=%CSV_PATH%
SET COMMAND=%COMMAND% Template=%TEMPLATE_PATH%
SET COMMAND=%COMMAND% RecipientField="Email1"
SET COMMAND=%COMMAND% AttachmentField="QRCodePath"

if not "%SENT_FOLDER%"=="" (
    SET COMMAND=%COMMAND% SentFolder="%SENT_FOLDER%"
)

echo Command to execute:
echo %COMMAND%
echo.

REM ============================================================================
REM CONFIRMATION
REM ============================================================================

echo [4/4] Ready to send emails...
echo.
echo WARNING: This will send emails to all recipients in the CSV file!
echo.
echo CSV file: %CSV_PATH%
echo Template: %TEMPLATE_PATH%
echo.
echo Press Ctrl+C to cancel, or
pause

REM ============================================================================
REM EXECUTE
REM ============================================================================

echo.
echo Executing ReliefJet mail merge...
echo.

%COMMAND%

SET ERRORLEVEL_RESULT=%ERRORLEVEL%

echo.
echo ============================================================================

if %ERRORLEVEL_RESULT%==0 (
    echo SUCCESS: Mail merge completed successfully!
    echo All emails have been sent.
) else if %ERRORLEVEL_RESULT%==1 (
    echo CANCELLED: Mail merge was cancelled by user.
) else (
    echo ERROR: Mail merge failed with error code %ERRORLEVEL_RESULT%
    echo.
    echo Common issues:
    echo   - Incorrect utility code (verify with ExecutorCli search)
    echo   - Invalid parameters (run: ExecutorCli -? -u %UTILITY_CODE%)
    echo   - Outlook not configured on this machine
    echo   - ReliefJet Professional Edition not licensed
    echo   - Template file format incorrect
)

echo ============================================================================
echo.

pause
exit /b %ERRORLEVEL_RESULT%
